/*
 * AUDIO CONTROLLER CLASS
 * AUTHOR: Fran Caamaño Martínez
 */

#ifndef BASICS_PROJECT_TEMPLATE_AUDIOCONTROLLER_HPP
#define BASICS_PROJECT_TEMPLATE_AUDIOCONTROLLER_HPP

namespace DuetClone {

    class AudioController {

    };

} // DuetClone

#endif //BASICS_PROJECT_TEMPLATE_AUDIOCONTROLLER_HPP
